import { Link } from 'react-router-dom'

export default function Home() {
  return (
    <div className="bg-[#0b0121] min-h-screen font-montserrat flex items-center justify-center px-5">
      <div className="max-w-[800px] w-full">
        <div className="text-center mb-16">
          <h1
            className="text-[72px] font-bold leading-none mb-6 bg-clip-text text-transparent"
            style={{
              backgroundImage: "linear-gradient(173.477deg, rgb(236, 236, 236) 20.345%, rgba(236, 236, 236, 0) 128.73%)",
              WebkitBackgroundClip: "text",
              WebkitTextFillColor: "transparent"
            }}
          >
            Figma to Code
          </h1>
          <p className="text-[rgba(236,236,236,0.65)] text-[24px] leading-[1.6]">
            Compare different Figma-to-code implementations
          </p>
        </div>

        <div className="grid md:grid-cols-2 gap-6">
          {/* Claude Card */}
          <Link to="/claude" className="group">
            <div className="bg-gradient-to-b from-[rgba(255,255,255,0.05)] to-transparent rounded-[20px] shadow-[0px_-2px_10px_0px_rgba(233,223,255,0.3),0px_-2px_40px_0px_rgba(187,155,255,0.15),inset_0px_0.5px_0px_0px_rgba(255,255,255,0.5)] p-12 hover:from-[rgba(255,255,255,0.08)] transition-all cursor-pointer h-full flex flex-col">
              <div className="mb-6">
                <div className="w-16 h-16 bg-gradient-to-br from-purple-500 to-blue-500 rounded-2xl flex items-center justify-center mb-6 shadow-[0px_0px_36px_0px_rgba(89,29,221,0.75)]">
                  <svg className="w-8 h-8 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4" />
                  </svg>
                </div>
                <h2 className="text-[#ececec] text-[36px] font-medium leading-[1.3] tracking-[-0.16px] mb-4">
                  Claude
                </h2>
                <p className="text-[#ececec] text-[16px] leading-[1.5] opacity-80">
                  Implementation generated by Claude AI with React, TypeScript, and Tailwind CSS
                </p>
              </div>
              <div className="mt-auto">
                <span className="text-white text-[16px] font-medium underline group-hover:opacity-80 transition-opacity">
                  View implementation →
                </span>
              </div>
            </div>
          </Link>

          {/* Locofy Card */}
          <Link to="/locofy" className="group">
            <div className="bg-gradient-to-b from-[rgba(255,255,255,0.05)] to-transparent rounded-[20px] shadow-[0px_-2px_10px_0px_rgba(233,223,255,0.3),0px_-2px_40px_0px_rgba(187,155,255,0.15),inset_0px_0.5px_0px_0px_rgba(255,255,255,0.5)] p-12 hover:from-[rgba(255,255,255,0.08)] transition-all cursor-pointer h-full flex flex-col">
              <div className="mb-6">
                <div className="w-16 h-16 bg-gradient-to-br from-pink-500 to-purple-500 rounded-2xl flex items-center justify-center mb-6 shadow-[0px_0px_36px_0px_rgba(201,37,171,0.75)]">
                  <svg className="w-8 h-8 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 21a4 4 0 01-4-4V5a2 2 0 012-2h4a2 2 0 012 2v12a4 4 0 01-4 4zm0 0h12a2 2 0 002-2v-4a2 2 0 00-2-2h-2.343M11 7.343l1.657-1.657a2 2 0 012.828 0l2.829 2.829a2 2 0 010 2.828l-8.486 8.485M7 17h.01" />
                  </svg>
                </div>
                <h2 className="text-[#ececec] text-[36px] font-medium leading-[1.3] tracking-[-0.16px] mb-4">
                  Locofy
                </h2>
                <p className="text-[#ececec] text-[16px] leading-[1.5] opacity-80">
                  Implementation generated by Locofy.ai design-to-code platform
                </p>
              </div>
              <div className="mt-auto">
                <span className="text-white text-[16px] font-medium underline group-hover:opacity-80 transition-opacity">
                  View implementation →
                </span>
              </div>
            </div>
          </Link>
        </div>

        <div className="mt-12 text-center">
          <p className="text-[rgba(236,236,236,0.5)] text-[14px]">
            Based on the Vaultflow SaaS Landing Page design from Figma Community
          </p>
        </div>
      </div>
    </div>
  )
}
